version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=application
      - MYSQL_PASSWORD=application
      - MYSQL_DATABASE=hhplus
    volumes:
      - ./data/mysql/:/var/lib/mysql
      - ./init/01-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./init/02-data.sql:/docker-entrypoint-initdb.d/02-data.sql

networks:
  default:
    driver: bridge